'use client';

import { ArrowRight, ArrowUpRight, BookOpen, Search } from 'lucide-react';
import { SteamArtwork } from './steam-artwork';
import { analysisPath, findStories, gameStories, originalAnalysis, storyMethodology, storyPath } from './editorial-data';

const sourceNames: Record<string, string> = { 'store.steampowered.com': 'Steam store', 'steamcommunity.com': 'Developer announcement', 'steamdb.info': 'SteamDB', 'howtomarketagame.com': 'How To Market A Game', 'newsletter.gamediscover.co': 'GameDiscoverCo', 'gameworldobserver.com': 'Game World Observer', 'gameifyouare.com': 'Game If You Are', 'derek-lieu.com': 'Derek Lieu', 'gamedeveloper.com': 'Game Developer', 'partner.steamgames.com': 'Steamworks', 'cbgamedev.com': 'Developer postmortem' };
function sourceLabel(url: string) { const host = new URL(url).hostname.replace(/^www\./, ''); return sourceNames[host] ?? host; }
export function EvidenceLinks({ urls }: { urls: string[] }) { return urls.length ? <div className="editorial-citations" aria-label="Evidence sources">{Array.from(new Set(urls)).map((url, i) => <a key={url} href={url} target="_blank" rel="noreferrer">{sourceLabel(url)}{urls.filter(u => sourceLabel(u) === sourceLabel(url)).length > 1 ? ` · ${i + 1}` : ''}<ArrowUpRight aria-hidden="true" /></a>)}</div> : null; }
function Notes({ title, items }: { title: string; items: string[] }) { return <section className="editorial-box"><h3>{title}</h3><ul>{items.map(item => <li key={item}>{item}</li>)}</ul></section>; }
function SourceRegister({ urls }: { urls: string[] }) { return <details className="editorial-sources" open><summary>Full source register · {urls.length} references</summary><ol>{urls.map(url => <li key={url}><a href={url} target="_blank" rel="noreferrer">{url}</a></li>)}</ol></details>; }
const valueText = (value: string | number | null) => value === null ? 'Not disclosed' : typeof value === 'number' ? value.toLocaleString('en-US') : value;

export function GameStories({ storyId, query, setQuery }: { storyId?: string; query: string; setQuery: (value: string) => void }) {
  const selected = gameStories.find(story => story.id === storyId);
  if (selected) return <section className="workbench editorial-view">
    <a className="editorial-back" href="/stories/">← All game stories</a>
    <header className="story-heading"><div><p className="section-kicker">GAME STORY · {selected.title}</p><h1>{selected.headline}</h1><p className="editorial-deck">{selected.deck}</p><p className="editorial-meta">Steam Discovery Research · {selected.readingMinutes} min narrative + evidence · Checked {selected.checkedAt}</p></div><SteamArtwork appId={String(selected.appId)} title={selected.title} priority /></header>
    <p className="editorial-status">{selected.releaseStatus}{'team' in selected && <> · {selected.team}</>} <a href={`/radar/?q=${selected.appId}`}>Inspect dated Steam evidence →</a></p>
    <nav className="editorial-jumps" aria-label="Story contents"><a href="#story-narrative">The story</a><a href="#story-kpis">KPIs & definitions</a><a href="#story-timeline">Campaign timeline</a><a href="#story-demand">Demand structure</a><a href="#story-build">Build transfer</a></nav>
    <div className="editorial-layout"><article className="editorial-prose" id="story-narrative"><p className="editorial-lead">{selected.marketQuestion}</p>{selected.story.map(section => <section key={section.heading}><h2>{section.heading}</h2><p>{section.body}</p><EvidenceLinks urls={section.sourceUrls} />{section.sourceUrls.length === 0 && <span className="editorial-meta">Steam Discovery interpretation / proposed experiment</span>}</section>)}</article><aside className="editorial-sidebar"><div className="editorial-box"><span className="section-kicker">PLAYER PROMISE</span><h3>{selected.playerPromise}</h3><p>{selected.hook}</p></div><div className="editorial-box"><h3>How to read this case</h3><p>Reported numbers retain the source’s window and definition. Our explanation is a hypothesis—not proof that a channel caused sales.</p><p>Sources: {selected.sourcePublications.join(' · ')}.</p><a href="/solo-lab/">Apply a lesson in Solo Lab <ArrowRight /></a></div></aside></div>
    <section id="story-kpis" className="editorial-section"><p className="section-kicker">EVIDENCE, NOT A SALES MODEL</p><h2>What we can actually measure</h2><div className="editorial-kpis">{selected.kpis.map(kpi => <article key={kpi.label}><span className="editorial-meta">{kpi.evidence}</span><h3>{kpi.label}</h3><strong>{valueText(kpi.value)}</strong><span>{kpi.unit}</span><p className="editorial-meta">{kpi.window}</p><p>{kpi.caveat}</p><EvidenceLinks urls={[kpi.source]} /></article>)}</div></section>
    <section id="story-timeline" className="editorial-section"><p className="section-kicker">WHEN · WHERE · WHAT CHANGED</p><h2>The campaign trace</h2><ol className="story-timeline">{selected.timeline.map((event, i) => <li key={`${event.when}-${i}`}><div><time>{event.when}</time><span>{event.channel}</span></div><article><h3>{event.action}</h3><p><b>Outcome:</b> {event.outcome ?? 'No measured result supplied.'}</p><p><b>Spend:</b> {event.spend ?? 'Not disclosed; not assumed to be zero.'}</p><p className="editorial-caution">{event.caveat}</p><EvidenceLinks urls={[event.source]} /></article></li>)}</ol></section>
    <section id="story-demand" className="editorial-section"><p className="section-kicker">MARKET STRUCTURE · EDITORIAL INTERPRETATION</p><h2>Who wants this, and what is the opening?</h2><dl className="editorial-facts">{[['Audience', selected.demand.audience], ['Player job', selected.demand.job], ['Demand trigger', selected.demand.trigger], ['Supply evidence', selected.demand.supply], ['Opening to test', selected.demand.opening], ['Still unproven', selected.demand.notProven]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><EvidenceLinks urls={selected.demand.sourceUrls} /><div className="editorial-three"><div><h3>Observed mechanism</h3><p>{selected.mechanism.observed}</p></div><div><h3>Our explanation</h3><p>{selected.mechanism.inference}</p></div><div><h3>Other explanations</h3><p>{selected.mechanism.confounds}</p></div></div><EvidenceLinks urls={selected.mechanism.sourceUrls} /></section>
    <section id="story-build" className="editorial-section"><p className="section-kicker">THE TRANSFER · NOT A CLONE</p><h2>What a solo developer or small team can test</h2><dl className="editorial-facts">{[['Borrow the principle', selected.buildTransfer.borrow], ['Change the expression', selected.buildTransfer.change], ['Proposed mini-demo', selected.buildTransfer.miniDemo], ['Technical cuts', selected.buildTransfer.technicalCut], ['Do not copy', selected.buildTransfer.doNotCopy], ['Proposed test', selected.buildTransfer.successTest]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p className="editorial-caution">These prototype ideas and gates are our proposals, not the original games’ production plans or validated market benchmarks.</p><Notes title="What can go wrong" items={selected.risks} /></section>
    <SourceRegister urls={selected.sourceUrls} /><div className="editorial-next"><a href="/analysis/">Read our cross-case analysis <ArrowRight /></a><a href="/solo-lab/">Find a two-week prototype <ArrowRight /></a></div>
  </section>;
  const visible = findStories(query);
  return <section className="workbench editorial-view"><div className="workspace-heading"><div><p className="section-kicker"><BookOpen aria-hidden="true" /> RESEARCH, ALREADY DIGESTED</p><h1>Understand the game.<br />Trace the demand. Build your test.</h1></div><p className="workspace-note">Game-level stories, dated KPIs and practical production choices. Read the analysis here; use the citations to check it.</p></div>
    <div className="editorial-start"><div><span className="section-kicker">STEAM DISCOVERY RESEARCH</span><h2>Steam marketing research for indie game teams.</h2><p>Compare indie game launches, wishlist campaigns and genre demand through dated evidence. Our source notes explain what each finding can support and where the uncertainty remains.</p></div><a className="editorial-primary-link" href="/reading/">Read the latest source notes <ArrowRight /></a></div>
    <div className="editorial-heading-row"><div><p className="section-kicker">GAME STORIES</p><h2>Follow the whole story—not just the headline.</h2></div><label className="editorial-search"><Search aria-hidden="true" /><span className="sr-only">Search game stories</span><input value={query} onChange={e => setQuery(e.target.value)} maxLength={120} placeholder="Game, genre, source or tactic…" /></label></div>
    <p className="editorial-meta" aria-live="polite">{visible.length} of {gameStories.length} digested stories · plus <a href="/case-studies/">11 earlier campaign timelines</a> and <a href="/games/">the full comparable library</a>.</p>
    <div className="story-grid">{visible.map(story => <a className="story-card" href={storyPath(story.id)} key={story.id}><SteamArtwork appId={String(story.appId)} title={story.title} /><div><p className="section-kicker">{story.title}</p><h3>{story.headline}</h3><p>{story.deck}</p><div className="story-card-evidence"><strong>{valueText(story.kpis[0].value)}</strong><span>{story.kpis[0].label} · {story.kpis[0].window}</span></div><span className="story-card-action">Read story, KPIs & build transfer <ArrowRight /></span></div></a>)}</div>
    {visible.length === 0 && <div className="editorial-box"><h3>No matching story</h3><p>Try a game, “survival”, “trailer”, “co-op” or a source name.</p><button onClick={() => setQuery('')}>Clear search</button></div>}
    <OriginalCards /><p className="editorial-method">{storyMethodology}</p>
  </section>;
}

function OriginalCards() { return <section className="editorial-section"><div className="editorial-heading-row"><div><p className="section-kicker">ORIGINAL ANALYSIS · STEAM DISCOVERY</p><h2>Three arguments. One development decision.</h2></div></div><div className="original-grid">{originalAnalysis.articles.map((article, i) => <a href={analysisPath(article.id)} key={article.id}><span className="original-number">0{i + 1}</span><p className="section-kicker">{article.kicker}</p><h3>{article.title}</h3><p>{article.deck}</p><span className="story-card-action">Read the full analysis <ArrowRight /></span></a>)}</div></section>; }

export function OriginalAnalysis({ articleId }: { articleId?: string }) {
  const article = originalAnalysis.articles.find(item => item.id === articleId);
  if (!article) return <section className="workbench editorial-view"><div className="workspace-heading"><div><p className="section-kicker">OUR RESEARCH DESK</p><h1>From public evidence to a decision you can test.</h1></div><p className="workspace-note">Original analysis, with explicit counterarguments. These are our conclusions—not republished articles or first-hand interviews.</p></div><OriginalCards /><p className="editorial-method">{originalAnalysis.disclosure}</p></section>;
  return <section className="workbench editorial-view"><a className="editorial-back" href="/analysis/">← Original analysis</a><header className="original-heading"><p className="section-kicker">{article.kicker} · ORIGINAL ANALYSIS</p><h1>{article.title}</h1><p className="editorial-deck">{article.deck}</p><p className="editorial-meta">{originalAnalysis.author} · {originalAnalysis.updatedAt} · {article.readingMinutes} min read</p></header><p className="editorial-thesis">{article.thesis}</p>
    <p className="editorial-status">Design update: this essay predates the team's existing-system brief. Its one-block production proposal is superseded by the <a href="/survival-demo/">city-escape GDD</a>, which includes guns, two herds, driving, camp construction and a boss kill. The cited market observations retain their original dates.</p>
    <div className="editorial-kpis">{article.evidenceCards.map(card => <article key={card.label}><h3>{card.label}</h3><strong>{card.value}</strong><p>{card.definition}</p>{card.sourceUrl ? <EvidenceLinks urls={[card.sourceUrl]} /> : <span className="editorial-meta">Our proposed design constraint</span>}</article>)}</div>
    <article className="editorial-prose original-prose">{article.sections.map(section => <section key={section.heading}><h2>{section.heading}</h2>{section.paragraphs.map(paragraph => <p key={paragraph}>{paragraph}</p>)}<EvidenceLinks urls={section.sourceUrls} /></section>)}</article>
    {article.comparison && <section className="editorial-section"><h2>{article.comparison.title}</h2><div className="editorial-table-wrap" tabIndex={0} role="region" aria-label={article.comparison.title}><table className="editorial-table"><thead><tr>{article.comparison.columns.map(column => <th key={column} scope="col">{column}</th>)}<th scope="col">Evidence</th></tr></thead><tbody>{article.comparison.rows.map((row, i) => <tr key={i}>{row.cells.map((cell, j) => <td key={j}>{cell}</td>)}<td><EvidenceLinks urls={row.sourceUrls} /></td></tr>)}</tbody></table></div><p className="editorial-caution">{article.comparison.caveat}</p></section>}
    <div className="editorial-two"><Notes title="What to do next" items={article.takeaways} /><Notes title="What would change our mind" items={article.falsifiers} /></div><div className="editorial-next"><a href={`/survival-demo/#${article.gddAnchor}`}>Apply this in the GDD <ArrowRight /></a>{article.relatedStoryIds.map(id => <a key={id} href={storyPath(id)}>{gameStories.find(story => story.id === id)?.title} story <ArrowRight /></a>)}</div><p className="editorial-method">{originalAnalysis.disclosure}</p><SourceRegister urls={article.sourceUrls} /></section>;
}

export { CityEscapeGdd as SurvivalDemoGdd } from './city-escape-gdd';
