'use client';
import { useState } from 'react';
import { ArrowDownToLine, ArrowUpRight, BarChart3, ShieldAlert } from 'lucide-react';
import { Button } from '@/components/ui/button';
import q1Data from './data/market-q1.json';
import q2Data from './data/market-q2.json';
import { niches } from './research-data';
import { SourceLink } from './explorer';

export const marketPeriods = ['2025', '2026-q1', '2026-q2'] as const;
export type MarketPeriod = typeof marketPeriods[number];
export function MarketPeriods({ period, setPeriod }: { period: MarketPeriod; setPeriod: (period: MarketPeriod) => void }) {
  const [allQ1Rows, setAllQ1Rows] = useState(false);
  const ranked = [...q1Data.rows].sort((a, b) => b.hits - a.hits || a.name.localeCompare(b.name));
  const rows = allQ1Rows ? ranked : ranked.slice(0, 14);
  return <section className="surface-panel quarterly-panel">
    <div className="surface-heading"><div><BarChart3 /><span><small>DEMAND / SUPPLY</small><strong>{period === '2025' ? '2025 genre outcomes vs. a 3-week demo' : period === '2026-q1' ? 'Q1 2026: published genre hit counts' : 'Q2 2026: coverage and available evidence'}</strong></span></div><SourceLink url={period === '2025' ? 'https://howtomarketagame.com/2026/01/27/what-the-hell-happened-in-2025/' : period === '2026-q1' ? 'https://howtomarketagame.com/2026/05/14/2026-q1-games/' : '/data/steam-june-2026-cohort.json'} label="Method/source" /></div>
    <div className="quarter-tabs" role="group" aria-label="Market data period">{marketPeriods.map(value => <a key={value} href={`/market/${value}/`} className={value === period ? 'active' : ''} aria-current={value === period ? 'page' : undefined} onClick={event => { if (!event.metaKey && !event.ctrlKey && !event.shiftKey && !event.altKey && event.button === 0) { event.preventDefault(); setPeriod(value); } }}><strong>{value === '2025' ? '2025 full year' : value === '2026-q1' ? '2026 · Q1' : '2026 · Q2'}</strong><span>{value === '2025' ? 'Genre supply + outcomes' : value === '2026-q1' ? 'Published hit counts' : 'Partial public evidence'}</span></a>)}</div>
    {period === '2025' && <><div className="quarter-context"><strong>Published annual cohort · HTMAG / VG Insights</strong><p>1,000+ reviews defines a “hit” in this analysis. Demo fit is our editorial scope judgment. Do not read these rates as a new team’s success probability.</p></div><div className="niche-table" tabIndex={0} role="region" aria-label="2025 genre demand and supply — scroll horizontally for all columns"><div className="niche-head"><span>Genre</span><span>Hits / supply</span><span>Hit rate</span><span>3-week fit</span><span>Read</span></div>{niches.map(item => <div className={`niche-row ${item.fit === 'High' ? 'is-opportunity' : ''}`} key={item.name}><strong>{item.name}</strong><span>{item.hits} / {item.supply.toLocaleString('en-US')}</span><span className="rate-cell"><b>{item.rate.toFixed(2)}%</b><i><em style={{ width: `${Math.min(item.rate * 4, 100)}%` }} /></i></span><span className={`fit fit-${item.fit.toLowerCase().replace('–', '-').replace(' ', '-')}`}>{item.fit}</span><small>{item.direction}</small></div>)}</div></>}
    {period === '2026-q1' && <>
      <div className="quarter-context"><strong>Releases: 1 Jan–31 Mar 2026 · measured 2 Apr · published 14 May</strong><p>Chris assigned a single genre to games reaching 1,000 reviews. These are early outcomes, not today’s review totals. Genre denominators were not published, so supply and hit-rate cells are intentionally blank.</p></div>
      <div className="quarter-stats"><div><strong>5,971</strong><span>Q1 releases</span></div><div><strong>96</strong><span>Overall 1K+ review bucket</span></div><div><strong>1.61%</strong><span>96 / 5,971 · calculated</span></div><div><strong>61.7%</strong><span>3,686 / 5,971 have 0–9 reviews</span></div></div>
      <div className="quarter-warning"><ShieldAlert /><p><strong>Source discrepancy:</strong> the 42 genre rows sum to 74, not the overall 96 hits. The source does not reconcile the 22-game gap. Its fallback text also says 63.2% low-review games; the published raw counts yield 61.7%. We show the arithmetic explicitly and do not repair the missing games by guessing.</p></div>
      <div className="quarter-table-wrap" tabIndex={0} role="region" aria-label="Q1 2026 genre outcomes — scroll horizontally for all columns"><table className="quarter-table"><thead><tr><th>Hand-assigned genre</th><th>Q1 2024 hits</th><th>Q1 2025 hits</th><th>Q1 2026 hits</th><th>2026 supply</th><th>2026 hit rate</th></tr></thead><tbody>{rows.map(row => <tr key={row.name}><th scope="row">{row.name === 'OWSC' ? 'Open-world survival craft' : row.name}</th><td>{row.q1_2024Hits}</td><td>{row.q1_2025Hits}</td><td className="current-quarter"><strong>{row.hits}</strong><i><em style={{ width: `${row.hits * 10}%` }} /></i></td><td><span title="Not published">—</span></td><td><span title="No valid denominator">—</span></td></tr>)}</tbody></table></div>
      <div className="quarter-table-footer"><span>“—” means unavailable, not zero. A zero hit count does not mean zero demand.</span><Button variant="outline" size="sm" onClick={() => setAllQ1Rows(!allQ1Rows)}>{allQ1Rows ? 'Show leading 14 genres' : 'Show all 42 genres'}</Button></div>
      <div className="quarter-warning neutral"><ShieldAlert /><p>Compare Q1-to-Q1 hit counts cautiously, not annual 2025 rates against early 2026 rates. Late-March games had much less time to accumulate reviews. Hand-assigned genres are not interchangeable with overlapping Steam tags.</p></div>
    </>}
    {period === '2026-q2' && <>
      <div className="q2-coverage"><span className="coverage-label">FULL QUARTER NOT VERIFIED · JUNE SUBSET BELOW</span><h3>Available Q2 evidence, with its limits visible.</h3><p>No publicly accessible, complete Q2 2026 genre-supply and 1,000-review outcome table was verified. A separate June-only public-store snapshot is available below. April–June totals and exact quarterly hit rates remain unknown.</p><SourceLink url="https://howtomarketagame.com/2026/" label="Checked HTMAG archive" /><p><strong>Different methodology:</strong> anonymous US catalogue, displayed June release dates, up to seven overlapping Steam tags, review-score counts observed 2 September. This is not Chris’s single-genre cohort, not indie-only, and not first-launch or equal-age performance.</p></div>
      <div className="quarter-stats"><div><strong>{q2Data.juneSubcohort.counts.supply.toLocaleString('en-US')}</strong><span>Included June-dated apps</span></div><div><strong>≥{q2Data.juneSubcohort.counts.hitsConfirmed}</strong><span>Confirmed 1K+ score-count games</span></div><div><strong>{q2Data.juneSubcohort.counts.unresolved.toLocaleString('en-US')}</strong><span>Threshold status unresolved</span></div><div><strong>—</strong><span>Exact hit rate: not available</span></div></div>
      <div className="quarter-warning"><ShieldAlert /><p>Missing numerical tooltips are <strong>not</strong> treated as zero reviews. Language-specific counts below 1,000 are also unresolved. A displayed count already above 1,000 confirms a minimum, not all-language total sales or reach. Lifetime reviews can predate a June 1.0 release.</p></div>
      <div className="quarter-table-wrap" tabIndex={0} role="region" aria-label="June 2026 tag evidence — scroll horizontally for all columns"><table className="quarter-table june-table"><thead><tr><th>Overlapping Steam tag</th><th>Included June supply</th><th>Confirmed 1K+ minimum</th><th>Unresolved</th><th>Exact hit rate</th></tr></thead><tbody>{q2Data.juneSubcohort.rows.map(row => <tr key={row.tagId}><th scope="row">{row.name}</th><td>{row.supply.toLocaleString('en-US')}</td><td>{row.hitsConfirmed > 0 ? `≥${row.hitsConfirmed}` : '0 confirmed'}</td><td>{row.unresolved.toLocaleString('en-US')}</td><td>—</td></tr>)}</tbody></table></div>
      <div className="quarter-table-footer"><span>24 overlapping tags; rows cannot be added. Counts apply only to the included June records. No genre ranking by incomplete rate.</span><a className="source-link" href="/data/steam-june-2026-cohort.json" download><ArrowDownToLine /> Download 2,102-row evidence</a></div>
      <details className="quarter-evidence"><summary>Show example games and lower-review comparators</summary><div className="june-examples">{q2Data.juneSubcohort.rows.filter(row => row.examples.high.length > 0).map(row => <article key={row.tagId}><h4>{row.name}</h4><span>Confirmed minimum example</span>{row.examples.high.slice(0, 1).map(game => <div key={game.appId}><SourceLink url={game.source} label={game.title} /><small>{game.displayedReviews.toLocaleString('en-US')} displayed scored reviews{game.languageSpecific ? ' · language-specific' : ''}</small></div>)}{row.examples.low.length > 0 && <><span>Below-threshold example</span>{row.examples.low.slice(0, 1).map(game => <div key={game.appId}><SourceLink url={game.source} label={game.title} /><small>{game.displayedReviews.toLocaleString('en-US')} displayed scored reviews · not a profitability judgment</small></div>)}</>}</article>)}</div></details>
      <details className="quarter-evidence"><summary>Coverage, reproducibility and source limitations</summary><p>Captured {q2Data.juneSubcohort.coverage.savedPages} contiguous public search pages on 2 September 2026, 17:40 UTC. Their displayed dates bracket June, but complete Steam coverage is not claimed. Two package rows were excluded; no duplicate June app IDs were found. Retrieval stopped after an HTTP error; April and most of May were not collected.</p><ul>{q2Data.caveats.map(caveat => <li key={caveat}>{caveat}</li>)}</ul><div className="quarter-source-list">{q2Data.sources.map(source => <SourceLink key={source.url} url={source.url} label={source.title} />)}</div></details>
      <div className="q2-coverage"><div className="q2-next-step"><strong>What would complete the quarterly comparison?</strong><p>A legitimate complete export with app IDs, first Steam release dates, consistent genre membership and review totals—including zero-review games. Recalculate both quarters using matching definitions and an explicit observation date. Do not combine a hand-classified hit count with an overlapping-tag supply denominator.</p><SourceLink url="https://gamalytic.com/game-list" label="Gamalytic export source" /><SourceLink url="https://partner.steamgames.com/doc/store/getreviews" label="Valve review definitions" /></div></div>
    </>}
  </section>;
}
