import { BookOpen, ShieldAlert, CheckCircle2 } from 'lucide-react';
import { SourceLink } from './explorer';
import auditData from './data/source-audit.json';
import hubArticles from './data/hub-articles.json';
import radarSnapshot from './data/radar-snapshot.json';
import storyExpansion from './data/story-expansion.json';
import { latestReadingUpdates } from './discovery-data';
import { ArticleSourceCatalog, ReferenceLink } from './source-references';
import referenceChecks from './data/reference-checks.json';

type AuditEntry = { url: string; status: string; note?: string; checkedAt?: string };
const entries = auditData.entries as AuditEntry[];
export function Methodology() {
  return <section className="workbench content-view methodology-view">
    <div className="workspace-heading"><div><p className="section-kicker"><BookOpen /> ABOUT THIS RESEARCH</p><h1>Evidence you can inspect.<br />Limits you can see.</h1></div><p className="workspace-note">Independent, AI-assisted editorial research for small PC game teams. Market baseline: 2 September 2026. Targeted small-team case, niche and playbook additions checked 8 September 2026. Older observations retain their individual dates. This is not a live analytics service, an independent financial audit or a Steam product.</p></div>
    <p className="research-byline">Published by Steam Discovery Research · Maintained by <a href="https://github.com/oguzhanozfe/steam-discovery">oguzhanozfe</a>. <a href="https://github.com/oguzhanozfe/steam-discovery/issues">Suggest a source or report a correction</a>.</p><div className="editorial-next"><a href="/stories/">Read the digested game stories</a><a href="/analysis/">Our original analysis</a><a href="/survival-demo/">The proposed mini-demo GDD</a><p>Our narratives synthesize cited public accounts; we did not interview these teams. Original arguments, prototype designs and test thresholds are our editorial work—not conclusions endorsed by the cited publications.</p></div>
    <div className="methodology-grid">
      <article id="attribution" className="surface-panel editorial-panel"><h2>Attribution & editorial contribution</h2><p>Original article titles, reporting, interviews and author arguments belong to their credited creators. Steam Discovery produces AI-assisted research notes and comparisons, not replacement editions of those publications.</p><ul><li>Source findings: link the exact article or data query next to the claim, preserving author, date, metric definition and access limits.</li><li>Our contribution: identify comparisons, causal hypotheses, concept designs, scope estimates and test gates as Steam Discovery proposals. A citation is not an author endorsement.</li><li>Quotation rule: any distinctive wording retained verbatim must be short, marked as a quotation, attributed and linked. Do not translate or lightly reword whole articles, reuse their structure as our own, or reproduce subscriber-only content.</li><li>Unknown metadata stays unknown. A page label for Steam data is not an original article title. Earlier source notes are not silently relabeled as newly verified.</li></ul><p>On {referenceChecks.checkedAt}, a targeted manual review compared selected site passages with 18 source articles. It found a Peglin timing error, corrected below. This sample is not a site-wide plagiarism certification or an independent audit of reported financial results.</p><p><a href="/data/reference-checks.json">Download this reference-check record</a> · <a href="/data/reference-metadata.json">Download original-source metadata & usage</a> · <a href="#article-sources">Article titles, authors & original links</a> · <a href="https://github.com/oguzhanozfe/steam-discovery/issues">Report an attribution or wording issue</a></p><h3>Correction: Peglin’s early wishlist timeline</h3><p>The previous page compared 384 festival-week wishlist additions with 485 in the preceding week. The original article describes those 485 as accumulating over roughly six months. The comparison and the unsupported weak-festival interpretation have been removed.</p><ReferenceLink url="https://howtomarketagame.com/2022/05/04/how-peglin-made-1049413-in-1-week/" /></article>
      <article className="surface-panel editorial-panel"><h2>What the labels mean</h2><dl><dt>Primary / developer reported</dt><dd>The developer, publisher or platform made the claim. This is attributed reporting, not an independent financial audit.</dd><dt>Observed</dt><dd>A public store or analytics page displayed a metric at the stated time. Reviews and concurrent players are not unit sales.</dd><dt>Estimated</dt><dd>A third-party model, with provider and snapshot date retained. Some case ranges show disagreement between models; SteamSpy owner bands are that provider’s estimate brackets. Neither is presented as a statistical confidence interval or paid sales.</dd><dt>Analysis / hypothesis</dt><dd>Our interpretation, concept, production estimate or experiment. It is not a measured market gap or a promise of sales.</dd></dl></article>
      <article className="surface-panel editorial-panel"><h2>How to use the numbers</h2><ul><li>Follow the citation next to the claim and check the time window and platform scope.</li><li>Free claims, wishlists, demo users, paid copies, reviews, CCU and gross revenue are separate measures.</li><li>Public marketing timelines establish sequence, not which channel caused a sale. Unknown spend does not mean zero spend.</li><li>This is a curated case library with survivor selection, not a random or exhaustive sample.</li><li>2025 hand-classified genres, early Q1 outcomes and June overlapping tags do not have comparable denominators.</li><li>The earlier three-week workspace assumes two senior developers, an artist, a PM and a marketer. Solo Lab instead assumes one experienced developer, ten workdays, 60 focused hours and 10 testing/outreach hours across fourteen calendar days. Demos are distinguished from microgame release candidates.</li></ul></article>
      <article id="sources" className="surface-panel editorial-panel"><h2>Sources and access</h2><p>Every case links to its original evidence. Article notes are our summaries, not reproductions of the newsletters. Paywalled or inaccessible material is not represented as fully read. A working link proves availability, not the truth of every claim.</p><p>The publication check below distinguishes responding URLs from restricted or untested sources. SteamDB was not batch-scraped; its cited pages remain separately attributed observations. Publishers may later move, edit or restrict their pages.</p><p><a href="/reading/">Browse the source reading room</a> · <a href="/data/source-audit.json" download>Link-check record</a> · <a href="/data/research-index.json">Research metadata</a> · <a href="/feed.xml">Research feed</a></p></article>
      <article className="surface-panel editorial-panel"><h2>Independence and artwork</h2><p>Steam Discovery is not affiliated with, sponsored by or endorsed by Valve, Steam, the games, or the publications cited here. Steam and the Steam logo are trademarks of Valve Corporation. We use our own site mark, not Valve’s logo.</p><p>Game names and official store capsule artwork belong to their respective rights holders. Capsules are linked from Steam’s asset service to identify games in editorial discussion; each game has a link to its official store page. Attribution is not a blanket licence or a statement that all artwork rights have been cleared.</p><p>No paid placement or affiliate links have been added to this research site. Publication does not guarantee permission for another use of the artwork. <SourceLink url="https://partner.steamgames.com/doc/marketing/branding" label="Valve branding guidance" /></p></article>
    </div>
    <section className="surface-panel editorial-panel"><div className="surface-heading"><div><CheckCircle2 /><span><small>SOURCE LEDGER UPDATED · {auditData.checkedAt}</small><strong>Original resources, with access status</strong></span></div></div><p>Baseline checks are dated 2 September; the 3 September reading expansion is a targeted addition, not a full recheck. These are availability and selected-source checks, not an audit of financial truth. “Responded” can include a login page or preview; the reading note retains its access limits. Restricted sources are not silently counted as verified.</p><div className="audit-summary">{Array.from(new Set(entries.map(entry => entry.status))).map(status => <span key={status}><strong>{entries.filter(entry => entry.status === status).length}</strong> {status}</span>)}</div><details className="audit-details" open><summary>Inspect all {entries.length} checked or explicitly excluded source URLs</summary><ol>{entries.map(entry => <li key={entry.url}><div><SourceLink url={entry.url} label={entry.url.replace(/^https?:\/\//, '')} /><span>{entry.status} · {entry.checkedAt}</span></div>{entry.note && <small>{entry.note}</small>}</li>)}</ol></details></section>
    <section className="surface-panel editorial-panel"><h2>Earlier publication checks · {latestReadingUpdates.checkedAt}</h2><p>Selected archive checks and new reading notes. Older game metrics have not been relabeled as fresh observations.</p><ul>{latestReadingUpdates.sourceChecks.map(source => <li key={source.url}><a href={source.url} target="_blank" rel="noreferrer">{source.source}</a> · <time dateTime={source.checkedAt}>{source.checkedAt}</time><p>{source.result}</p></li>)}</ul></section>
    <section className="surface-panel editorial-panel"><h2>Small-team hub update · {hubArticles.checkedAt}</h2><p>{radarSnapshot.coverage}</p><p>{radarSnapshot.reviewMethod} {radarSnapshot.ownerMethod} {radarSnapshot.timing}</p><p>The full catalog is downloaded in the browser; search, comparison and a device-local watchlist require JavaScript. Saved games are not an automated monitoring service. Manual refreshes are documented in the repository.</p><p><a href="/data/hub-articles.json">Playbooks and source-access ledger</a> · <a href="/data/hub-cases.json">New cases and KPI citations</a> · <a href="/data/hub-niches.json">Niche sample definitions</a> · <a href="/data/radar-catalog.json">Dated catalog snapshot</a></p></section>
    <section className="surface-panel editorial-panel"><h2>Story expansion · {storyExpansion.updatedAt}</h2><p>{storyExpansion.stories.length} additional game-level narratives, each with dated KPIs, a campaign trace, source-access notes and an editorial prototype proposal.</p><p>{storyExpansion.methodology}</p><p><a href="/data/game-stories.json">All stories and citations</a> · <a href="/data/story-expansion.json">This batch and its source-access ledger</a></p></section>
    <ArticleSourceCatalog />
    <div className="inline-note"><ShieldAlert /><p><strong>Correction standard:</strong> when a claim is contradicted, remove or qualify it and update the dated research snapshot. Recheck live sources before committing a development budget. Do not infer certainty from the site’s design.</p></div>
  </section>;
}
