import { BookOpen, ShieldAlert, CheckCircle2 } from 'lucide-react';
import { SourceLink } from './explorer';
import auditData from './data/source-audit.json';

type AuditEntry = { url: string; status: string; note?: string; checkedAt?: string };
const entries = auditData.entries as AuditEntry[];
export function Methodology() {
  return <section className="workbench content-view methodology-view">
    <div className="workspace-heading"><div><p className="section-kicker"><BookOpen /> ABOUT THIS RESEARCH</p><h1>Evidence you can inspect.<br />Limits you can see.</h1></div><p className="workspace-note">Independent, AI-assisted editorial research for small PC game teams. Market baseline: 2 September 2026. New game stories, survival evidence, original analysis and source notes checked 3 September 2026. This is not a live analytics service, an independent financial audit or a Steam product.</p></div>
    <div className="editorial-next"><a href="/">Read the digested game stories</a><a href="/analysis/">Our original analysis</a><a href="/survival-demo/">The proposed mini-demo GDD</a><p>Our narratives synthesize cited public accounts; we did not interview these teams. Original arguments, prototype designs and test thresholds are our editorial work—not conclusions endorsed by the cited publications.</p></div>
    <div className="methodology-grid">
      <article className="surface-panel editorial-panel"><h2>What the labels mean</h2><dl><dt>Primary / developer reported</dt><dd>The developer, publisher or platform made the claim. This is attributed reporting, not an independent financial audit.</dd><dt>Observed</dt><dd>A public store or analytics page displayed a metric at the stated time. Reviews and concurrent players are not unit sales.</dd><dt>Estimated</dt><dd>A third-party model, with provider and snapshot date retained. A range shows disagreement between models—not a statistical confidence interval.</dd><dt>Analysis / hypothesis</dt><dd>Our interpretation, concept, production estimate or experiment. It is not a measured market gap or a promise of sales.</dd></dl></article>
      <article className="surface-panel editorial-panel"><h2>How to use the numbers</h2><ul><li>Follow the citation next to the claim and check the time window and platform scope.</li><li>Free claims, wishlists, demo users, paid copies, reviews, CCU and gross revenue are separate measures.</li><li>Public marketing timelines establish sequence, not which channel caused a sale. Unknown spend does not mean zero spend.</li><li>This is a curated case library with survivor selection, not a random or exhaustive sample.</li><li>2025 hand-classified genres, early Q1 outcomes and June overlapping tags do not have comparable denominators.</li><li>All three-week scope judgments assume two senior developers, one artist, a PM and a marketing manager. They describe a prototype, not a complete game.</li></ul></article>
      <article className="surface-panel editorial-panel"><h2>Sources and access</h2><p>Every case links to its original evidence. Article notes are our summaries, not reproductions of the newsletters. Paywalled or inaccessible material is not represented as fully read. A working link proves availability, not the truth of every claim.</p><p>The publication check below distinguishes responding URLs from restricted or untested sources. SteamDB was not batch-scraped; its cited pages remain separately attributed observations. Publishers may later move, edit or restrict their pages.</p><p><a href="/reading/">Browse the source reading room</a> · <a href="/data/source-audit.json" download>Download the link-check record</a></p></article>
      <article className="surface-panel editorial-panel"><h2>Independence and artwork</h2><p>Steam Discovery is not affiliated with, sponsored by or endorsed by Valve, Steam, the games, or the publications cited here. Steam and the Steam logo are trademarks of Valve Corporation. We use our own site mark, not Valve’s logo.</p><p>Game names and official store capsule artwork belong to their respective rights holders. Capsules are linked from Steam’s asset service to identify games in editorial discussion; each game has a link to its official store page. Attribution is not a blanket licence or a statement that all artwork rights have been cleared.</p><p>No paid placement or affiliate links have been added to this research site. Publication does not guarantee permission for another use of the artwork. <SourceLink url="https://partner.steamgames.com/doc/marketing/branding" label="Valve branding guidance" /></p></article>
    </div>
    <section className="surface-panel editorial-panel"><div className="surface-heading"><div><CheckCircle2 /><span><small>SOURCE LEDGER UPDATED · {auditData.checkedAt}</small><strong>Original resources, with access status</strong></span></div></div><p>Baseline checks are dated 2 September; the 3 September reading expansion is a targeted addition, not a full recheck. These are availability and selected-source checks, not an audit of financial truth. “Responded” can include a login page or preview; the reading note retains its access limits. Restricted sources are not silently counted as verified.</p><div className="audit-summary">{Array.from(new Set(entries.map(entry => entry.status))).map(status => <span key={status}><strong>{entries.filter(entry => entry.status === status).length}</strong> {status}</span>)}</div><details className="audit-details"><summary>Inspect all {entries.length} checked or explicitly excluded source URLs</summary><ol>{entries.map(entry => <li key={entry.url}><div><SourceLink url={entry.url} label={entry.url.replace(/^https?:\/\//, '')} /><span>{entry.status} · {entry.checkedAt}</span></div>{entry.note && <small>{entry.note}</small>}</li>)}</ol></details></section>
    <div className="inline-note"><ShieldAlert /><p><strong>Correction standard:</strong> when a claim is contradicted, remove or qualify it and update the dated research snapshot. Recheck live sources before committing a development budget. Do not infer certainty from the site’s design.</p></div>
  </section>;
}
