'use client';
import { ArrowRight, Trees, ShieldAlert, Hammer, Compass, BookOpen } from 'lucide-react';
import { Button } from '@/components/ui/button';
import data from './data/survival-research.json';
import { SourceLink, EvidenceBadge } from './explorer';
import { SteamArtwork } from './steam-artwork';
import { AdSlot } from './ad-slot';

export function SurvivalResearch({ build }: { build: (hypothesis?: string) => void }) {
  return <section className="workbench content-view survival-view">
    <div className="workspace-heading"><div><p className="section-kicker"><Trees /> GENRE FIELD GUIDE · 2025 → 2026</p><h1>Open-world survival craft.<br /><span className="heading-subtitle">Borrow the promise. Constrain the world.</span></h1></div><p className="workspace-note">Eight core cases—not a market census. Full-game scope: very high. A constrained three-week slice: possible.</p></div>
    <div className="survival-intro"><div><span>THE PLAYER PROMISE</span><h2>A place to make yours.<br />A reason to leave it.</h2><p>{data.summary}</p></div><ol>{data.definitions.playerLoop.map((step, index) => <li key={step}><b>{String(index + 1).padStart(2, '0')}</b><span>{step}</span></li>)}</ol></div>
    <nav className="field-guide-nav" aria-label="Survival craft guide contents"><a href="#survival-evidence">01 · Demand evidence</a><a href="#survival-cases">02 · Eight OWSC cases</a><a href="#survival-prototypes">03 · Prototype ideas</a><a href="#survival-execution">04 · Execution plan</a></nav>


    <section id="survival-evidence" className="survival-section"><div className="section-title"><Compass /><span><small>DEMAND / SUPPLY</small><strong>Strong signals. Different denominators.</strong></span></div><div className="survival-evidence-grid">{data.marketEvidence.map((item, index) => <article key={item.period}><span>{item.period}</span><strong>{index === 0 ? '15 / 72' : index === 1 ? '4 hits' : '≥2 of 5 included'}</strong><small>{index === 0 ? '20.83% historical cohort ratio' : index === 1 ? 'Genre supply not published' : 'June subset · 1 unresolved · not a rate'}</small><p>{item.claim}</p><SourceLink url={item.source} label="Original evidence" /><p className="evidence-limit">{item.caveat}</p>{'manifest' in item && <a className="source-link" href={item.manifest}>Inspect June records ↗</a>}</article>)}</div><div className="survival-theses">{data.demandVersusSupply.map(item => <article key={item.claim}><h3>{item.claim}</h3><p>{item.basis}</p><div>{item.sources.map((url, index) => <SourceLink key={url} url={url} label={`Evidence ${index + 1}`} />)}</div><small>{item.caveat}</small></article>)}</div></section>

    <section className="surface-panel editorial-panel"><h2>Five recognizable player promises</h2><div className="promise-grid">{data.recognizablePromises.map(item => <article key={item.promise}><h3>{item.promise}</h3><p>{item.visibleProof}</p><span>{item.cases.join(' · ')}</span><small><strong>Test:</strong> {item.demoTest}</small></article>)}</div><p className="method-note">These are editorial design patterns, not statistically proven gaps. {data.definitions.classification}</p></section>

    <AdSlot placement="genre-between-demand-and-cases" />
    <section id="survival-cases" className="survival-section"><div className="section-title"><BookOpen /><span><small>CASE EVIDENCE</small><strong>What to borrow—and what not to clone.</strong></span></div><p className="survival-definition">{data.definitions.metricPolicy}</p><div className="survival-case-index">{data.cases.map(game => <a href={`#survival-${game.id}`} key={game.id}>{game.title}</a>)}</div><div className="survival-case-grid">{data.cases.map(game => <article className="survival-case" id={`survival-${game.id}`} key={game.id}>
      <a className="survival-art" href={`https://store.steampowered.com/app/${game.appId}/`} target="_blank" rel="noreferrer" aria-label={`${game.title} official Steam store`}><SteamArtwork appId={String(game.appId)} title={game.title} /></a>
      <div className="survival-case-body"><div className="survival-case-meta"><span>{game.earlyAccessDate?.startsWith('2026') || game.fullReleaseDate?.startsWith('2026') ? '2026 RELEASE SIGNAL' : 'HISTORICAL REFERENCE'}</span><SourceLink url={`https://store.steampowered.com/app/${game.appId}/`} label="Steam" /></div><h3>{game.title}</h3><p className="survival-positioning">{game.positioning}</p><small>{game.developer} · {game.earlyAccessDate ? `Early Access: ${game.earlyAccessDate}` : ''}{game.fullReleaseDate ? ` · 1.0: ${game.fullReleaseDate}` : ''}</small>
      <div className="survival-metrics"><div><strong>{game.observedMetrics.steamDbReviews.toLocaleString('en-US')}</strong><span>SteamDB aggregate reviews</span></div><div><strong>{game.observedMetrics.peakCCU.toLocaleString('en-US')}</strong><span>Peak CCU · {game.observedMetrics.peakDate}</span></div></div><p className="survival-metric-source">Observed {game.observedMetrics.asOf} · <SourceLink url={game.observedMetrics.source} label="SteamDB snapshot source" /></p>
      {game.reportedMilestone ? <div className="survival-milestone"><EvidenceBadge value="Developer reported" /><strong>{'qualifier' in game.reportedMilestone ? `${game.reportedMilestone.qualifier} ` : ''}{game.reportedMilestone.value.toLocaleString('en-US')} <span>{game.reportedMilestone.metric}</span></strong><small>{'periodEnd' in game.reportedMilestone ? `Period ends ${game.reportedMilestone.periodEnd}` : `Published ${game.reportedMilestone.publicationDate}`}</small><SourceLink url={game.reportedMilestone.source} label="Milestone evidence" /><p>{game.reportedMilestone.caveat}</p></div> : <p className="survival-no-sales">No verified unit-sales disclosure included here. Do not convert reviews or CCU into paid copies.</p>}
      <p className="survival-promise"><strong>Player promise</strong>{game.playerPromise}</p>
      <details className="survival-detail"><summary>Marketing mechanism + feasible demo spin <ArrowRight /></summary><h4>What the source actually shows</h4><p>{game.marketingMechanism.observed}</p><SourceLink url={game.marketingMechanism.source} label="Marketing source" /><h4>Our interpretation</h4><p>{game.marketingMechanism.inference}</p><p><strong>Spend:</strong> {game.marketingMechanism.spend}</p>{'caveat' in game.marketingMechanism && <p>{game.marketingMechanism.caveat}</p>}<div className="survival-spin"><span>PROPOSED THREE-WEEK SLICE · NOT MARKET-VALIDATED</span><h4>{game.threeWeekSpin.title}</h4><p>{game.threeWeekSpin.scope}</p><p><strong>Technical cut:</strong> {game.threeWeekSpin.technicalCut}</p><p><strong>Recordable payoff:</strong> {game.threeWeekSpin.clip}</p></div><p className="survival-risk"><ShieldAlert /><span>{game.fullGameRisk}</span></p><div className="survival-sources">{game.sourceUrls.map((url, index) => <SourceLink key={url} url={url} label={`${index + 1}. ${new URL(url).hostname.replace('www.', '')}`} />)}</div></details>
      </div>
    </article>)}</div></section>

    <section className="surface-panel editorial-panel downside-panel"><h2>Keep lower-review comparators in view</h2><p>The June snapshot also includes these tagged games. They prevent a winner-only reading of the niche; they do not establish that either developer lost money.</p><div className="downside-grid">{data.downsideControls.map(game => <article key={game.appId}><a href={game.source} target="_blank" rel="noreferrer"><SteamArtwork appId={String(game.appId)} title={game.title} /></a><div><h3>{game.title}</h3><strong>{game.displayedScoredReviews} displayed scored reviews</strong><small>June release date: {game.displayedReleaseDate} · observed {game.asOf}</small><p>{game.lesson}</p><SourceLink url={game.source} label="Official store" /></div></article>)}</div></section>

    <section id="survival-prototypes" className="survival-section"><div className="section-title"><Hammer /><span><small>PROTOTYPE EXAMPLES · EDITORIAL JUDGMENT</small><strong>Four bounded prototypes to investigate.</strong></span></div><div className="survival-directions">{data.recommendedDemoDirections.map(direction => <article key={direction.name}><span className="direction-number">0{direction.rank}</span><h3>{direction.name}</h3><div className="direction-comps">{direction.comparables.map(title => { const reference = data.cases.find(game => game.title === title); return <a key={title} href={`#survival-${reference?.id}`}>{title}</a>; })}</div><p>{direction.scopeRationale}</p><h4>Hypothesis</h4><p>{direction.demandHypothesis}</p><h4>What is not proven</h4><p>{direction.notProven}</p><h4>Biggest delivery risk</h4><p>{direction.largestRisk}</p><Button variant="outline" onClick={() => build(`${direction.name}: ${direction.demandHypothesis} Compare ${direction.comparables.join(', ')}. Unproven: ${direction.notProven} Delivery risk: ${direction.largestRisk}`)}>Use in experiment brief <ArrowRight /></Button></article>)}</div></section>

    <section id="survival-execution" className="surface-panel editorial-panel"><h2>Three weeks: finish one honest loop.</h2><p>{data.threeWeekExecution.capacityAssumption}</p><p><strong>Deliverable:</strong> {data.threeWeekExecution.deliverable}</p><div className="survival-week-grid">{[data.threeWeekExecution.week1, data.threeWeekExecution.week2, data.threeWeekExecution.week3].map((week, index) => <article key={week}><span>WEEK 0{index + 1}</span><p>{week}</p></article>)}</div><div className="methodology-grid"><div><h3>Hard scope cuts</h3><ul>{data.threeWeekExecution.hardCuts.map(cut => <li key={cut}>{cut}</li>)}</ul></div><div><h3>Proposed validation gates</h3><ul>{data.threeWeekExecution.proposedValidationGates.map(gate => <li key={gate}>{gate}</li>)}</ul></div></div><p><a href="/sprint-plan/">Check Steam release constraints and the full sprint plan →</a></p></section>
    <section className="survival-section"><div className="section-title"><BookOpen /><span><small>READ THE ORIGINALS</small><strong>Continue with the source material.</strong></span></div><div className="survival-reading">{data.furtherReading.map(item => <article key={item.url}><SourceLink url={item.url} label={item.title} /><p>{item.why}</p></article>)}</div></section>
  </section>;
}
